import { readFileSync, writeFileSync } from "fs";
import { ethers } from "ethers";
import "dotenv/config";



// Ganache RPC
const RPC_URL = "http://127.0.0.1:7545";

// Private key from Ganache (the one you used in hardhat config)
const PRIVATE_KEY =
  "0x99d8f2202e03882bb4387fd8fbcfa8916e9f7d9bd9f4f2f37483d6bc90f482cd";

// Path to artifact generated by Hardhat compile
const artifactPath =
  "./artifacts/contracts/Verification.sol/Verification.json";

async function main() {
  const artifact = JSON.parse(readFileSync(artifactPath, "utf8"));
  const abi = artifact.abi;
  const bytecode = artifact.bytecode;

  const provider = new ethers.JsonRpcProvider(RPC_URL);
  const wallet = new ethers.Wallet(PRIVATE_KEY, provider);

  console.log("Deployer address:", await wallet.getAddress());

  const factory = new ethers.ContractFactory(abi, bytecode, wallet);

  console.log("Deploying Verification contract...");
  const contract = await factory.deploy();
  await contract.waitForDeployment();

  const address = await contract.getAddress();
  console.log("✅ Verification deployed to:", address);

  writeFileSync("contract-address.txt", address, "utf8");
console.log("📄 Saved contract address to contract-address.txt");
}

main().catch((e) => {
  console.error("❌ Deploy failed:", e);
  process.exit(1);
});
