import { readFileSync } from "fs";
import { ethers } from "ethers";

// Ganache RPC
const RPC_URL = "http://127.0.0.1:7545";

// Private key from Ganache (the one you used in hardhat config)
const PRIVATE_KEY =
  "0x80d6b5629c313ec6ba692d64821c4d74ea615170485ec132c06995abd91ba147";

// Path to artifact generated by Hardhat compile
const artifactPath =
  "./artifacts/contracts/Verification.sol/Verification.json";

async function main() {
  const artifact = JSON.parse(readFileSync(artifactPath, "utf8"));
  const abi = artifact.abi;
  const bytecode = artifact.bytecode;

  const provider = new ethers.JsonRpcProvider(RPC_URL);
  const wallet = new ethers.Wallet(PRIVATE_KEY, provider);

  console.log("Deployer address:", await wallet.getAddress());

  const factory = new ethers.ContractFactory(abi, bytecode, wallet);

  console.log("Deploying Verification contract...");
  const contract = await factory.deploy();
  await contract.waitForDeployment();

  const address = await contract.getAddress();
  console.log("✅ Verification deployed to:", address);
}

main().catch((e) => {
  console.error("❌ Deploy failed:", e);
  process.exit(1);
});
